# Generated by Django 2.0.3 on 2018-03-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='Demand_file',
            new_name='demand_file',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='Order_file',
            new_name='order_file',
        ),
    ]
