# Generated by Django 2.0.3 on 2018-03-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20180312_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda_diaria', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('demanda_promedio', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='ses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.DecimalField(decimal_places=1, default=0.0, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='dma',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='ses',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
    ]
